# Project: LLM
# Makefile created by Red Panda C++ 3.2.2958

CXX      = "g++.exe"
CC       = "gcc.exe"
WINDRES  = "windres.exe"
RM       = del /q /f
CD       = cd /d
LIBS     = "-Wl,--stack,12582912" "E:/RedPanda/Console/(Control)/Debug/LLM/libcurl/lib/libcurl.lib"
INCS     = "-IE:/RedPanda/Console/(Control)/Debug/LLM/libcurl/include/curl"
CXXINCS  = "-IE:/RedPanda/Console/(Control)/Debug/LLM/libcurl/include/curl"
CXXFLAGS = $(CXXINCS) "-g3" "-pipe" "-Wall" "-D_DEBUG"
CFLAGS   = $(INCS) "-g3" "-pipe" "-Wall" "-D_DEBUG"
WINDRESFLAGS = 
RES      = DeepSeek_private.res
OBJ      = main.o $(RES)
BIN      = LLM.exe
LINKOBJ  = "main.o" "DeepSeek_private.res"
CLEANOBJ = "main.o" "DeepSeek_private.res" "LLM.exe"

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) >NUL 2>&1

LLM.exe: $(OBJ)

	$(CXX) $(LINKOBJ) -o "LLM.exe" $(LIBS)

main.o: main.cpp
	$(CXX) -c "main.cpp" -o "main.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

DeepSeek_private.res: DeepSeek_private.rc 
	$(WINDRES) -i "DeepSeek_private.rc" --input-format=rc -o "DeepSeek_private.res" -O coff $(WINDRESFLAGS) 

